mib=
{
     beam_id=2;
     bcch_band_id=3;//1~56
     #sib freq
     bcch_fre_id=1;//0~3
     bcch_slot_start= 4;
     frame_off=0;
     sys_info_ver_tag=0;
     sys_sh_fra_num=1;
     d_to_beam_center=3;
     meas_normal_ra= 16;
     hot_info_indication=false;
     pcch_band_id=1;
     pcch_fre_id=1;
     naviInfo_band_id=4;
     naviInfo_fre_id=1;
     naviInfo_slot_ass=3;
     mib_Re_Fra_num=0;
     spare=0;  
};
