recfg_wx=
{
	rrc_tran_iden=1;

	rrc_con_recfg_r1_ies=
	{
		# meas_cfg=
		# {
		# 	meas_cfg_present=true;
		# 	meas_gap_cfg_list_present=true;
		# 	s_mea_sure_present=true;
		# 	#area_mode == 0 常规模式
		# 	beam_index1=1;
		# 	frame_off1=1;
		# 	fcch_band_id1=6;
		# 	fcch_freq_id1=1;
		# 	meas_nom_ratio1="dB9";

		# 	beam_index2=2;
		# 	frame_off2=2;
		# 	fcch_band_id2=7;
		# 	fcch_freq_id2=1;
		# 	meas_nom_ratio2="dB9";

		# 	beam_index3=3;
		# 	frame_off3=3;
		# 	fcch_band_id3=8;
		# 	fcch_freq_id3=1;
		# 	meas_nom_ratio3="dB9";

		# 	beam_index4=4;
		# 	frame_off4=4;
		# 	fcch_band_id4=9;
		# 	fcch_freq_id4=1;
		# 	meas_nom_ratio4="dB9";

		# 	rssi_normal=32;
			
		# 	report_cfg=
		# 	{
		# 		thr_hold_present=true;
		# 		report_geo_grap_info_present=true;
		# 		off_set=1;
		# 		hysteresis=1;
		# 		time_to_trigger="ms0";
		# 		filter_coe_ent="fc0";
		# 		report_geo_grap_info="True";
		# 	}
		# }
		
		
		# mobility_contro_cfg=
		# {
		# 	mobility_contro_present=false;
		# 	rach_indi_tor_present=true;
		# 	target_beam_index=1;
		# 	target_beam_id=24;
		# 	target_bcch_band_id=9;
		# 	t304="ms800";
		# 	rach_indi_tor="True";
		# }

		redio_resour_cfg_dedi_present=true;
		redio_resour_cfg_dedi=
		{
			#srb_to_add_present=true;
			drb_to_rel_list=
			{
				drb_to_rel_list_present=false;
				drb_id=3;
			}
			drb_to_add_cfg=
			{
				drb_to_add_mod_list_present=true;
				sdap_cfg=
				{
					sdap_cfg_present=true;
					map_qos_flows_to_add_present=true;
					map_qos_flow_to_rel_present=false;
					pdu_ses_id=2;
					sdap_header_dl="absent";
					sdap_header_ul="absent";
					default_drb=false;
					qfi=3;
				}

				drb_id=5;

				pdcp_cfg=
				{
					pdcp_cfg_present=true;
					dis_timer_present=true;
					rlc_tm_present=true;
					#integ_pro_present=false;
					dis_timer="infinity";
					# stat_rep_req=true;
					# integ_pro="enabled";
				}

				rlc_cfg=
				{
					rlc_cfg_present=true;
					# t_poll_retran="ms2100";
					# poll_pdu="p32";
					# poll_byte="kB128";
					# max_retx_thres_hold="t2";
					# t_reord="ms2100";
					# t_status_proh="ms600";
				}

				log_chan_cfg=
				{
					log_chan_cfg_present=true;
					ul_spec_para_present=true;
					log_chan_goup_present=true;
					priority=1;
					log_chan_goup=1;
					prio_bit_rate="kBps16";
					buck_size_dura="ms60";
				}
			}

			# peri_bsr_timer_cfg=
			# {
			# 	peri_bsr_timer_present=true;
			# 	peri_bsr_timer="rf5";
			# }

			phy_chan_list_cfg=
			{
                phy_chan_list_cfg_present=true;
				#area_mode == 0 常规模式
				band_id_present=true;
				freq_id_present=true;
				slot_ass_present=true;
				sche_type_present=true;
				voice_type_present=true;
				s_rnti=2;
				band_id=45;
				freq_id=1;
				chan_type="pDCH11";
				direc_t="biDirection";
				slot_ass=4;
				#sche_type="Static";
				voice_type="kbps2point4";				
			}

			security_cfg=
			{
				secu_cfg_present=true;
				sec_pay_load_Present=true;
				coph_alg="nea0";

			}

		}

	}
}
