/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <unistd.h>
#include <cassert> 
#include "cy_log.h"
#include "cy_vxi11.h"

//#include "CY52_Target.h"
#include "cy_multilink.h"
//#include "CY52_HashTable.h"
#include "cy_server.h"
static long int g_nClientId = 0;

int device_init()
{
	g_nClientId = 0;
	return 0;
}

int device_uninit()
{
	
	return 0;
}

long device_getclientid()
{
	return g_nClientId = (g_nClientId+1)%MAX_SUPPORTED_VXI11_CLIENTID_COUNT;
}

/*初始化link相关参数*/
int device_createlink(int nSubInstrmentIndex,long lid)
{
	/*创建发送缓存内存块*/
	auto replyMap = AfxGetContext()->phtVXI11Reply;
	if(replyMap.find(lid) == replyMap.end())
	{
		std::shared_ptr<CY_VXI11_COMMAND_REPLY_CONTEXT> preplyContext = std::make_shared<CY_VXI11_COMMAND_REPLY_CONTEXT>();
		if(preplyContext == NULL)
		{
			VLE_LOGE(CONTROL_LEVEL_ERROR,"CY_VXI11_EC_SRVFUNCREPLYMEMORYERROR[%d]",CY_VXI11_EC_SRVFUNCREPLYMEMORYERROR);
			return CY_VXI11_EC_SRVFUNCREPLYMEMORYERROR;
		}
		preplyContext->pszCommand.reset(new char[MAX_SUPPORTED_VXI11_COMMANDCACHE_LENGTH+MAX_SUPPORTED_VXI11_PER_COMMAND_LENGTH], std::default_delete<char[]>());
		if(preplyContext->pszCommand == NULL)
		{
			VLE_LOGE(CONTROL_LEVEL_ERROR,"CY_VXI11_EC_SRVFUNCCOMMANDCONTEXTMEMORYERROR[%d]",CY_VXI11_EC_SRVFUNCCOMMANDCONTEXTMEMORYERROR);
			return CY_VXI11_EC_SRVFUNCCOMMANDCONTEXTMEMORYERROR;
		}

		preplyContext->nSubInstruId	  = nSubInstrmentIndex;
		preplyContext->lid			  = lid;
		preplyContext->nszCommandHead = 0;
		preplyContext->nszCommandTail = 0;
		preplyContext->nszCommandMaxLength = MAX_SUPPORTED_VXI11_COMMANDCACHE_LENGTH;

		preplyContext->pszReply.reset(new char[MAX_SUPPORTED_VXI11_REPLYCACHE_LENGTH+MAX_SUPPORTED_VXI11_PER_REPLY_LENGTH], std::default_delete<char[]>());
		if(preplyContext->pszReply == NULL)
		{
			VLE_LOGE(CONTROL_LEVEL_ERROR,"CY_VXI11_EC_SRVFUNCREPLYCONTEXTMEMORYERROR[%d]",CY_VXI11_EC_SRVFUNCREPLYCONTEXTMEMORYERROR);
			return CY_VXI11_EC_SRVFUNCREPLYCONTEXTMEMORYERROR;
		}
		preplyContext->nszReplyHead = 0;
		preplyContext->nszReplyTail = 0;
		preplyContext->nszReplyMaxLength = MAX_SUPPORTED_VXI11_COMMANDCACHE_LENGTH;
		replyMap[lid] = preplyContext;
		
		//AfxGetContext()->subInstruManager.CreateSubInstrumentContext(nSubInstrmentIndex,(void*)preplyContext);
		
		VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_write_commandcache create lid,%ld",lid);
	}
	return 0;
}

/*释放连接*/
int device_destroylink(long lid)
{
	CY_VXI11_COMMAND_REPLY_CONTEXT* preplyContext = NULL;
	auto &replyMap = AfxGetContext()->phtVXI11Reply;
	replyMap.erase(lid);
	
	return 0;
}

/*保存命令到对应缓存队列中*/
int device_write_commandcache(long lid,char* pszData,int nDataLength)
{
	int i;
	char szT[MAX_SUPPORTED_VXI11_PER_COMMAND_LENGTH];
	int nHead,nTail,nStart,nSeg;
	
	auto &replyMap = AfxGetContext()->phtVXI11Reply;
	assert(replyMap.find(lid) != replyMap.end());
	std::shared_ptr<CY_VXI11_COMMAND_REPLY_CONTEXT> preplyContext = replyMap[lid];

	/*拷贝数据到缓冲区尾部*/
	memcpy(preplyContext->pszCommand.get()+preplyContext->nszCommandTail,pszData,nDataLength);
	preplyContext->nszCommandTail = (preplyContext->nszCommandTail + nDataLength);
	if(preplyContext->nszCommandTail > MAX_TCPTRANS_RECV_LENGTH)
	{
		memcpy(preplyContext->pszCommand.get(),preplyContext->pszCommand.get()+preplyContext->nszCommandMaxLength,
			preplyContext->nszCommandTail-preplyContext->nszCommandMaxLength);
			preplyContext->nszCommandTail = preplyContext->nszCommandTail-preplyContext->nszCommandMaxLength;
	}

	/*检测完整指令*/
	nHead = preplyContext->nszCommandHead;
	nTail = preplyContext->nszCommandTail;
	nSeg = preplyContext->nszCommandMaxLength-1;
	nStart = nHead;
	if(nTail < nHead)
	{
		nTail += preplyContext->nszCommandMaxLength;
	}
	
	for(i = nHead;i < nTail;i ++)
	{
		if(preplyContext->pszCommand.get()[i%preplyContext->nszCommandMaxLength] == '\n')
		{
			/*segment*/
			if((i > nSeg) && (nStart < nSeg))
			{
				memcpy(szT,preplyContext->pszCommand.get()+nStart,nSeg-nStart);
				memcpy(szT+nSeg-nStart,preplyContext->pszCommand.get(),i-nSeg);
				AfxGetContext()->pMultiLink->PostScpiCommand(MLINK_SCPISOURCE_TYPE_VXI,preplyContext.get(),szT,i-nStart+1);// 长度加1，保证'\n'符号被保存
			}
			else
			{
				AfxGetContext()->pMultiLink->PostScpiCommand(MLINK_SCPISOURCE_TYPE_VXI,preplyContext.get(),preplyContext->pszCommand.get()+nStart,i-nStart+1);// 长度加1，保证'\n'符号被保存
			}
			nStart = i+1;
		}
	}
	preplyContext->nszCommandHead = nStart%preplyContext->nszCommandMaxLength;
	return 0;
}

/*发送回复数据到发送缓冲区*/
#define RESET_HEAD_TAIL_4_LOOPBACK 1

int device_send_reply(void* pvClientContext,const char* pszData,int nDataLength)
{
	CY_VXI11_COMMAND_REPLY_CONTEXT* preplyContext = (CY_VXI11_COMMAND_REPLY_CONTEXT*)pvClientContext;

	/*注意：检测首尾是否相碰撞*/
	if((preplyContext->nszReplyTail<preplyContext->nszReplyHead) &&
		((preplyContext->nszReplyTail+nDataLength)>preplyContext->nszReplyHead))
	{
		VLE_LOGE(CONTROL_LEVEL_ERROR,"CY_VXI11_EC_SRVFUNCSENDBUFFERHEADTAILERROR[%d]:Tail:%d,Head:%d,Length:%d",
			CY_VXI11_EC_SRVFUNCSENDBUFFERHEADTAILERROR,preplyContext->nszReplyTail,preplyContext->nszReplyHead,nDataLength);
		return CY_VXI11_EC_SRVFUNCSENDBUFFERHEADTAILERROR;
	}
	/*拷贝数据到环形缓冲区*/
	if((preplyContext->nszReplyTail + nDataLength) > preplyContext->nszReplyMaxLength)
	{
#if RESET_HEAD_TAIL_4_LOOPBACK
		preplyContext->nszReplyTail = 0;
        preplyContext->nszReplyHead = 0;
        
        printf("line %d nszReplyTail %d\n",__LINE__,preplyContext->nszReplyTail);
        printf("line %d MAX %d nDataLength %d,offset %d\n",__LINE__,preplyContext->nszReplyMaxLength,nDataLength,preplyContext->nszReplyMaxLength - preplyContext->nszReplyTail);
		memcpy(preplyContext->pszReply.get()+preplyContext->nszReplyTail,pszData,nDataLength);
		preplyContext->nszReplyTail += nDataLength;
#else
        printf("line %d nszReplyTail %d\n",__LINE__,preplyContext->nszReplyTail);
        printf("line %d MAX %d nDataLength %d,offset %d\n",__LINE__,preplyContext->nszReplyMaxLength,nDataLength,preplyContext->nszReplyMaxLength - preplyContext->nszReplyTail);
		memcpy(preplyContext->pszReply.get()+preplyContext->nszReplyTail,pszData,preplyContext->nszReplyMaxLength-preplyContext->nszReplyTail);
		memcpy(preplyContext->pszReply.get(),pszData+preplyContext->nszReplyMaxLength-preplyContext->nszReplyTail,
			preplyContext->nszReplyTail + nDataLength-preplyContext->nszReplyMaxLength);
		preplyContext->nszReplyTail = preplyContext->nszReplyTail + nDataLength-preplyContext->nszReplyMaxLength;
#endif
	}
	else
	{
		memcpy(preplyContext->pszReply.get()+preplyContext->nszReplyTail,pszData,nDataLength);
		preplyContext->nszReplyTail += nDataLength;
	}
	return 0;
}

/*读缓冲区读取回复数据流*/
int device_read_reply(long lid,long requestSize,Device_ReadResp* pResult)
{

	auto &replyMap = AfxGetContext()->phtVXI11Reply;
	assert(replyMap.find(lid) != replyMap.end());
	std::shared_ptr<CY_VXI11_COMMAND_REPLY_CONTEXT> preplyContext = replyMap[lid];
	
	
	if(preplyContext->nszReplyHead == preplyContext->nszReplyTail)
	{
#ifdef DEBUG_SCPI_FUNC_TRACE	
		VLE_LOGE(CONTROL_LEVEL_ERROR,"CY_VXI11_EC_SRVFUNCREPLYREADEHASHERROR-1[%d]",CY_VXI11_EC_SRVFUNCREPLYREADEHASHERROR);
#endif
		return -1;
	}
	
	/*移动缓冲区，保证其线性*/
	if(preplyContext->nszReplyHead > preplyContext->nszReplyTail)
	{
		if((preplyContext->nszReplyTail+preplyContext->nszReplyMaxLength-preplyContext->nszReplyHead) > MAX_SUPPORTED_VXI11_PER_REPLY_LENGTH)
		{
			pResult->error = 10;
			VLE_LOGE(CONTROL_LEVEL_ERROR,"CY_VXI11_EC_SRVFUNCREPLYMOVEREADOUTOFRANGEERROR[%d]:move replycache out of range error,%d",
				CY_VXI11_EC_SRVFUNCREPLYMOVEREADOUTOFRANGEERROR,preplyContext->nszReplyTail+preplyContext->nszReplyMaxLength-preplyContext->nszReplyHead);
			return CY_VXI11_EC_SRVFUNCREPLYMOVEREADOUTOFRANGEERROR;
		}
		memcpy(preplyContext->pszReply.get()+preplyContext->nszReplyMaxLength,preplyContext->pszReply.get(),
			preplyContext->nszReplyTail+preplyContext->nszReplyMaxLength-preplyContext->nszReplyHead);
	}

	/*判断是否分段*/
	if((preplyContext->nszReplyTail-preplyContext->nszReplyHead) < requestSize)
	{
		pResult->reason = 0x04;
		pResult->data.data_len = preplyContext->nszReplyTail-preplyContext->nszReplyHead;
        //printf("LINE %d nszReplyTail %d,nszReplyHead %d requestSize %ld pResult->data.data_len = %d\n"
        //    ,__LINE__,preplyContext->nszReplyTail,preplyContext->nszReplyHead,requestSize,pResult->data.data_len);
#if RESET_HEAD_TAIL_4_LOOPBACK
#else
        if(preplyContext->nszReplyTail < preplyContext->nszReplyHead)//loop back
        {
        	pResult->data.data_len = preplyContext->nszReplyTail + preplyContext->nszReplyMaxLength - preplyContext->nszReplyHead;
        	printf("LINE %d nszReplyTail %d,nszReplyHead %d requestSize %ld pResult->data.data_len = %d\n"
            	,__LINE__,preplyContext->nszReplyTail,preplyContext->nszReplyHead,requestSize,pResult->data.data_len);
        }
#endif
	}
	else
	{
		pResult->reason = 0x01;
		pResult->data.data_len = requestSize-preplyContext->nszReplyHead;
        printf("LINE %d nszReplyTail %d,nszReplyHead %d requestSize %ld pResult->data.data_len = %d\n"
            ,__LINE__,preplyContext->nszReplyTail,preplyContext->nszReplyHead,requestSize,pResult->data.data_len);
	}
	pResult->error = 0;
	pResult->data.data_val = preplyContext->pszReply.get()+preplyContext->nszReplyHead;
	preplyContext->nszReplyHead = (preplyContext->nszReplyHead+pResult->data.data_len)%preplyContext->nszReplyMaxLength;
#ifdef INVALID_INFO	
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"result.error:%ld,result.data.val:%s,result.data.length:%u",
			pResult->error,pResult->data.data_val,pResult->data.data_len);	
#endif
	return 0;
}

Device_Error *
device_abort_1_svc(Device_Link *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_abort_1_svc");
#endif
	return &result;
}

Create_LinkResp *
create_link_1_svc(Create_LinkParms *argp, struct svc_req *rqstp)
{
	static Create_LinkResp  result;
	int	  nSubInstrmentIndex = 1; // 不需要支持多设备，写死即可
	
	/*
	 * insert server code here
	 */
	
	nSubInstrmentIndex = strtol(argp->device+4,NULL,10);
#ifdef DEBUG_SCPI_FUNC_TRACE 	
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"create_link_1_svc,devicename:%s,clientid:%ld,nSubInstrmentIndex:%d",argp->device,argp->clientId,nSubInstrmentIndex);
#endif
	//if(!AfxGetContext()->subInstruManager.CheckSubInstrument(nSubInstrmentIndex))
	{
	  result.error = 0;
	  result.lid = SUBINSTRU_KEY_VALUE(nSubInstrmentIndex,device_getclientid());//3232246579; 	// 本地IP地址
	  result.abortPort = 1025;
	  result.maxRecvSize = 14000;

#ifndef DEBUG_VXI_SRVFUNC

	  /*创建发送队列*/
	  if(device_createlink(nSubInstrmentIndex,result.lid) < 0)
	  {
		  result.error = 20;
		  result.lid = 522133279;
		  result.abortPort = 0;
		  result.maxRecvSize = 0;
		  VLE_LOGE(CONTROL_LEVEL_ERROR,"device_createlink fail!");
		  return &result;
	  }
#endif
	  VLE_LOGE(CONTROL_LEVEL_DEBUG,"create_link_1_svc ok!");
	}
	/*else
	{
	  result.error = 21;
	  result.lid = 522133279;
	  result.abortPort = 0;
	  result.maxRecvSize = 0;
	  VLE_LOGE(CONTROL_LEVEL_ERROR,"device_createlink fail!");
	}*/
	return &result;
}

Device_WriteResp *
device_write_1_svc(Device_WriteParms *argp, struct svc_req *rqstp)
{
	static Device_WriteResp  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 	 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_write_1_svc,clientid:%ld,data:%s,length:%d",argp->lid,argp->data.data_val,argp->data.data_len);
#endif

#if DEBUG_VXI_SRVFUNC
	if(argp->lid == 1)
	  {
		  VLE_LOGE(CONTROL_LEVEL_INFO,"device_write_1_svc IN argp->lid");
		  if(!strncmp(argp->data.data_val, "*IDN?",strlen("*IDN?")))
		  {
			 VLE_LOGE(CONTROL_LEVEL_INFO,"IDN? BOCK");
			 result.error = 0;
			 result.size = sizeof(argp->data.data_val);
		  }
		  else if(!strncmp(argp->data.data_val, "FETC?",strlen("FETC?")))
		  {
			 VLE_LOGE(CONTROL_LEVEL_INFO,"FETC? BOCK");
			 usleep(1000000);
			 result.error = 0;
			 result.size = sizeof(argp->data.data_val);
		  }
	  }

#else
#if 1
	auto lid = argp->lid;
	if(!strncmp(argp->data.data_val, "*IDN?",strlen("*IDN?")))
	  {
		 //CY_VXI11_COMMAND_REPLY_CONTEXT* preplyContext = NULL;
		 auto &replyMap = AfxGetContext()->phtVXI11Reply;
		 assert(replyMap.find(lid) != replyMap.end());
		 std::shared_ptr<CY_VXI11_COMMAND_REPLY_CONTEXT> preplyContext = replyMap[lid];
	
		
		 char szDeviceIDN[256] = {0};
		 sprintf(szDeviceIDN,"0.0.1");
		 device_send_reply(preplyContext.get(),szDeviceIDN, strlen(szDeviceIDN));
		 
		 result.error = 0;
		 result.size = sizeof(argp->data.data_val);
	  }

#endif

	/*发送到缓冲区中*/
	if(device_write_commandcache(argp->lid,argp->data.data_val,argp->data.data_len) < 0)
	{
		result.error = 19;
		VLE_LOGE(CONTROL_LEVEL_ERROR,"device_write_commandcache fail");
	}
	else
	{
		result.error = 0;
	}
	result.size = argp->data.data_len;
#endif
	return &result;
}

#ifdef DEBUG_VXI_SRVFUNC
char device_info[] = {"Iphone,5s,A1053,10.3"};
#endif

Device_ReadResp *
device_read_1_svc(Device_ReadParms *argp, struct svc_req *rqstp)
{
	static Device_ReadResp  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_read_1_svc,clientid:%ld,requestSize:%ld",argp->lid,argp->requestSize);
#endif
	
#ifdef DEBUG_VXI_SRVFUNC
	if( argp->lid == 1 )
	  {
	    result.error = 0;
	    result.reason = 0x04;
	    result.data.data_len = sizeof(device_info);
	    result.data.data_val = device_info;
		VLE_LOGE(CONTROL_LEVEL_INFO,"result.data.data_val = %s" , result.data.data_val);
	  }
#else
	if(device_read_reply(argp->lid,argp->requestSize,&result) < 0)
	{
		result.error = 15;
	    result.reason = 0x04;
		
#ifdef DEBUG_SCPI_FUNC_TRACE
		VLE_LOGE(CONTROL_LEVEL_ERROR,"device_read_reply fail!");
#endif
	}
#endif
	return &result;
}

Device_ReadStbResp *
device_readstb_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_ReadStbResp  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_readstb_1_svc");
#endif
	return &result;
}

Device_Error *
device_trigger_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_trigger_1_svc");
#endif
	return &result;
}

Device_Error *
device_clear_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_clear_1_svc");
#endif
	return &result;
}

Device_Error *
device_remote_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_remote_1_svc");
#endif
	return &result;
}

Device_Error *
device_local_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_local_1_svc");
	return &result;
}

Device_Error *
device_lock_1_svc(Device_LockParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_lock_1_svc");
#endif
	return &result;
}

Device_Error *
device_unlock_1_svc(Device_Link *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_unlock_1_svc");
#endif
	return &result;
}

Device_Error *
device_enable_srq_1_svc(Device_EnableSrqParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_enable_srq_1_svc");
#endif
	return &result;
}

Device_DocmdResp *
device_docmd_1_svc(Device_DocmdParms *argp, struct svc_req *rqstp)
{
	static Device_DocmdResp  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_docmd_1_svc");
#endif
	return &result;
}

Device_Error *
destroy_link_1_svc(Device_Link *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"destroy_link_1_svc,lid:%ld",*argp);
#endif

#ifndef DEBUG_VXI_SRVFUNC
	if(device_destroylink(*argp) < 0)
	{
		result.error = 17;
		VLE_LOGE(CONTROL_LEVEL_ERROR,"device_destroylink fail");
	}
#endif
	return &result;
}

Device_Error *
create_intr_chan_1_svc(Device_RemoteFunc *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"create_intr_chan_1_svc");
#endif
	return &result;
}

Device_Error *
destroy_intr_chan_1_svc(void *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"destroy_intr_chan_1_svc");
#endif
	return &result;
}

void *
device_intr_srq_1_svc(Device_SrqParms *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
#ifdef DEBUG_SCPI_FUNC_TRACE 
	VLE_LOGE(CONTROL_LEVEL_DEBUG,"device_intr_srq_1_svc");
#endif
	return (void *) &result;
}
